name: Issue Waiting Report
on: 
  issue_comment: 
    types: [created]
    
jobs: 
  issue-report:
    name: Issue Report
    if: ${{ (github.event.sender.login == github.event.issue.user.login) && contains(github.event.issue.labels.*.name, '等待反馈') }}
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/simple-issue-labeler
      - name: Issue Labeler
        uses: andymckay/labeler@1.0.4
        with: 
          remove-labels: "等待反馈"
          add-labels: "等待确认"
          repo-token: ${{ secrets.FORLIY_ACCESS_TOKEN }}
