name: Publish Release
on:
  push:
    tags:
      - v3.**.**
jobs:
  run-test:
    name: Run Test
    runs-on: ubuntu-latest
    steps:
      # 检出仓库代码
      - name: Check Out Repo
        uses: actions/checkout@v2
        with:
          submodules: true

      # setup Java
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 8

      # setup Gradle
      - name: Gradle Publish Release
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.4
          arguments: clean build test

  publish-release:
    name: Publish Release
    runs-on: ubuntu-latest
    needs: run-test
    steps:
      # 检出仓库代码
      - name: Check Out Repo
        uses: actions/checkout@v2
        with:
          submodules: true

      # setup Java
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 8
          cache: 'gradle'

      # the gpg
      - name: Decode Gpg File
        run: |
          echo "${{ secrets.GPG_B64 }}" > ForteScarlet.gpg.b64
          base64 -d ForteScarlet.gpg.b64 > ForteScarlet.gpg

      # setup Gradle
      - name: Gradle Publish Release
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.4
          arguments: clean build test publishToSonatype closeAndReleaseStagingRepository -DisSnapshot=false -DreleaseOnly -Psigning.secretKeyRingFile=ForteScarlet.gpg -Psigning.keyId=${{ secrets.SIGN_KEY_ID }} -Psigning.password=${{ secrets.SIGN_PASS }} -Psonatype.username=${{ secrets.OSS_USERNAME }} -Psonatype.password=${{ secrets.OSS_PASSWORD }} -Porg.gradle.jvmargs="org.gradle.jvmargs=-Xmx4G -Xms4G -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8" -Porg.gradle.workers.max=16 -Porg.gradle.parallel=true

  create-release:
    name: Create release
    runs-on: ubuntu-latest
    needs: publish-release
    permissions:
      contents: write
    steps:
      # 检出仓库代码
      - name: Check Out Repo
        uses: actions/checkout@v2
        with:
          submodules: true

        # Create gitHub release
      - name: Create Github Release
        uses: softprops/action-gh-release@v0.1.14
        with:
          token: ${{ secrets.PUSH_TOKEN }}
          body_path: .changelog/${{ github.ref_name }}.md
          generate_release_notes: true
          prerelease: ${{ contains(github.ref_name, 'preview') || contains(github.ref_name, 'beta') || contains(github.ref_name, 'alpha') }}
          # draft: true

  publish-snapshot:
    name: Publish snapshot
    runs-on: ubuntu-latest
    needs: publish-release
    steps:
      # 检出仓库代码
      - name: Check out repo
        uses: actions/checkout@v2
        with:
          submodules: true

      # setup Java
      - name: Setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 8
          cache: 'gradle'

      # the gpg
      - name: Decode gpg file
        run: |
          echo "${{ secrets.GPG_B64 }}" > ForteScarlet.gpg.b64
          base64 -d ForteScarlet.gpg.b64 > ForteScarlet.gpg

      # setup Gradle
      - name: Gradle publish snapshot
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.4
          arguments: clean build test publishToSonatype closeAndReleaseStagingRepository -DisSnapshot=true -DsnapshotOnly -Psigning.secretKeyRingFile=ForteScarlet.gpg -Psigning.keyId=${{ secrets.SIGN_KEY_ID }} -Psigning.password=${{ secrets.SIGN_PASS }} -Psonatype.username=${{ secrets.OSS_USERNAME }} -Psonatype.password=${{ secrets.OSS_PASSWORD }}  -Porg.gradle.jvmargs="org.gradle.jvmargs=-Xmx4G -Xms4G -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8" -Porg.gradle.workers.max=16 -Porg.gradle.parallel=true

  deploy-doc:
    if: github.repository == 'ForteScarlet/simpler-robot'
    name: Deploy-doc
    needs: publish-release
    runs-on: ubuntu-latest
    steps:
      # 检出仓库代码
      - name: Check out repo
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
          submodules: true

      # setup Java
      - name: Setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 11
          cache: 'gradle'

      - name: Create gradle.properties
        run: |
          echo "org.gradle.parallel=true" > gradle.properties
          echo "org.gradle.workers.max=16" >> gradle.properties
          echo "org.gradle.jvmargs=-Xmx8G -Xms2G -XX:MaxMetaspaceSize=1G -Dfile.encoding=UTF-8" >> gradle.properties

      # setup Gradle
      - name: Gradle generate documentation
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.4
          arguments: clean build dokkaHtmlMultiModuleAndPost -Porg.gradle.daemon=false -DisSnapshot=false

      # https://github.com/marketplace/actions/github-pages-action
      - name: Push to doc repository
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PUSH_TOKEN }}
          external_repository: simple-robot-library/simbot3-main-apiDoc
          publish_branch: gh-pages  # default: gh-pages
          keep_files: true
          publish_dir: ./dokka/html
          full_commit_message: Publish ${{ github.ref_name }} documentation


