name: Publish Snapshot
on: # push
  push:
    branches:
      - v3-dev
      - v3-dev-snapshot**
    paths:
      - '**src/**/kotlin/**.kt'
      - '**src/**/java/**.java'
      - 'buildSrc'
jobs:
  publish-snapshot:
    name: Publish snapshot
    runs-on: ubuntu-latest
    steps:
      # 检出仓库代码
      - name: Check out repo
        uses: actions/checkout@v2
        with:
          submodules: true

      # setup Java
      - name: Setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 8

      # the gpg
      - name: Decode gpg file
        run: |
          echo "${{ secrets.GPG_B64 }}" > ForteScarlet.gpg.b64
          base64 -d ForteScarlet.gpg.b64 > ForteScarlet.gpg

      # setup Gradle
      - name: Gradle publish snapshot
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.4
          arguments: clean build test publishToSonatype closeAndReleaseStagingRepository -DisSnapshot=true -DsnapshotOnly -Psigning.secretKeyRingFile=ForteScarlet.gpg -Psigning.keyId=${{ secrets.SIGN_KEY_ID }} -Psigning.password=${{ secrets.SIGN_PASS }} -Psonatype.username=${{ secrets.OSS_USERNAME }} -Psonatype.password=${{ secrets.OSS_PASSWORD }}  -Porg.gradle.jvmargs="org.gradle.jvmargs=-Xmx4G -Xms4G -XX:MaxMetaspaceSize=512m -Dfile.encoding=UT-8" -Porg.gradle.workers.max=16 -Porg.gradle.parallel=true



